# Project information

site_name: Security Workshops
site_description: 'A collection of AWS Security related workshops'
site_author: 'aws-security-workshops@amazon.com'
site_url: 'https://awssecworkshops.com'

# Repository
repo_name: 'aws-samples/aws-security-workshops'
repo_url: 'https://github.com/aws-samples/aws-security-workshops'

# Copyright
copyright: '&copy; 2020, Amazon Web Services, Inc. or its affiliates. All rights reserved.'

# Configuration
theme:
  name: 'material'
  logo: 'assets/images/aws_smile_logo.png'
  favicon: 'assets/images/aws-favicon.ico'
  feature:
    tabs: true
  custom_dir: 'docs/theme'

# Customization
extra_css:
  - 'stylesheets/custom.css'
extra_javascript:
  - 'javascripts/extra.js'
extra:
  social:
    - type: 'home'
      link: 'https://awssecworkshops.com'
    - type: 'shield'
      link: 'https://aws.amazon.com/security/'
    - type: 'twitter'
      link: 'https://twitter.com/awssecurityinfo?lang=en'
    - type: 'rss'
      link: 'https://aws.amazon.com/blogs/security/'

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details

# Navigation
nav:
  - Home: 'index.md'
  - Getting Started: 'getting-started.md'
  - Builder Sessions:
    - Directory: 'builder-sessions/index.md'
    - 'Hands-on with Amazon GuardDuty': 'https://hands-on-guardduty.awssecworkshops.com/'
    - 'Native Infrastructure Security': 'https://ec2-infra-sec.awssecworkshops.com/'
    - Permission Boundaries: 
      - Build Phase: 'builder-sessions/permission-boundary/build.md'
      - Verify Phase: 'builder-sessions/permission-boundary/verify.md'
    - 'Using AWS Secrets Manager with Amazon RDS and AWS Fargate': 'https://secrets-manager.awssecworkshops.com/RDSFargate/'
  - Workshops: 
    - 'Directory': 'workshops/index.md'
  - Contributing: 'contribute.md'
  - License: 'license.md'